#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stay
  pod 'FSCalendar'
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'StayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StayUITests' do
    # Pods for testing
  end

end
